config/routes.rb
EverblogRails::Application.routes.draw do

  root to: 'evernotes#common'

  CONFIG['header_links'].each do |link|
    match link['path'], to: 'evernotes#common'
    match File.join(link['path'], 'feed'), to: 'evernotes#common' if link['resource']['type'] == 'notebook'
  end

  match '/:created/', to: 'evernotes#show', created: /[1-9]\d{9}/, as: :note

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include ApplicationHelper

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/evernote_controller.rb
class EvernoteController < ApplicationController
  def index
    require 'evernote'

    user_store_url = "https://sandbox.evernote.com/edam/user"

    config = {
       :username => 'tylerlong',
       :password => 'fihu2zim',
       :consumer_key => 'tylerlong',
       :consumer_secret => 'c9a682d60f9a442c'
    }

    user_store = Evernote::UserStore.new(user_store_url, config)

    auth_result = user_store.authenticate
    auth_token = auth_result.authenticationToken
    user = auth_result.user

    note_store_url = "http://sandbox.evernote.com/edam/note/#{user.shardId}"
    note_store = Evernote::NoteStore.new(note_store_url)

    notebook = note_store.listNotebooks(auth_token).select do |notebook|
      notebook.name.downcase == "blog"
    end[0]

    @notes = note_store.findNotes(auth_token, Evernote::EDAM::NoteStore::NoteFilter.new(notebookGuid: notebook.guid), 0, 1000).notes

    @note = note_store.getNote(auth_token, @notes[1].guid, true, true, true, true)
  end
end

app/controllers/evernotes_controller.rb
require 'evernote'
require 'date'
require 'nokogiri'

module EvernoteAuthentication
  @@updated = 1.year.ago
  def authenticate
    user_store_url = "https://#{CONFIG['evernote']['domain']}/edam/user"
    user_store = Evernote::UserStore.new(user_store_url, CONFIG['evernote']['config'])
    authentication = user_store.authenticate
    @@shard_id, @@auth_token = authentication.user.shardId, authentication.authenticationToken
    note_store_url = "http://#{CONFIG['evernote']['domain']}/edam/note/#{@@shard_id}"
    @@note_store = Evernote::NoteStore.new(note_store_url)
    @@updated = 1.second.ago
  end
  def note_store
    @@note_store
  end
  def auth_token
    @@auth_token
  end
  def shard_id
    @@shard_id
  end
  def session_timeout_check
    authenticate if 1.second.ago - @@updated > 2400 # refresh authentication every 40 minutes.
  end
end

module EvernoteHelper
  def get_notes_list(notebook_name, page)
    notebook = note_store.listNotebooks(auth_token).select { |notebook| notebook.name.force_encoding('utf-8') == notebook_name }.first || not_found
    note_filter = Evernote::EDAM::NoteStore::NoteFilter.new(notebookGuid: notebook.guid,
      order: Evernote::EDAM::Type::NoteSortOrder::CREATED, ascending: false)
    notes = note_store.findNotes(auth_token, note_filter, (page - 1) * CONFIG['page_size'], CONFIG['page_size'] + 1).notes
    notes.map { |note| Hashie::Mash.new({ title: note.title.force_encoding('utf-8'),
      created: note.created, snippet: extract_snippet(get_note_by_guid(note.guid, false)[:content]),
      updated: note.updated }) }
  end

  def get_tags_by_note_guid(guid)
    note_store.getNoteTagNames(auth_token, guid)
  end

  def get_note_by_guid(guid, with_resource_data = false)
    note = note_store.getNote(auth_token, guid, true, with_resource_data, false, false) || not_found
    note = { title: note.title.force_encoding('utf-8'), content: extract_content(note.content),
      created: note.created, updated: note.updated, resources: note.resources,
      tags: get_tags_by_note_guid(note.guid) }
    embed_images(note)
  end

  def get_note_by_created(created, with_resource_data = false)
    note_filter = Evernote::EDAM::NoteStore::NoteFilter.new(words: "created:#{created}",
      order: Evernote::EDAM::Type::NoteSortOrder::CREATED, ascending: true)
    note = note_store.findNotes(auth_token, note_filter, 0, 1).notes.first || not_found
    get_note_by_guid(note.guid, with_resource_data)
  end
end

class EvernotesController < ApplicationController
  before_filter :session_timeout_check

  def common
    link = CONFIG['header_links'].select do |link|
      add_trailing_slash(link['path']) == first_token(request.path)
    end.first || not_found
    resource = link['resource']
    case resource['type']
      when 'notebook'
        @title = link['text']
        handle_notebooks(resource['name'])
      when 'note'
        handle_note(resource['guid'])
      else
        not_found
    end
  end

  def show
    created = DateTime.strptime(params[:created], '%s').strftime('%Y%m%dT%H%M%SZ')
    @note = get_note_by_created(created, true) || not_found
  end


  private

    include EvernoteAuthentication
    include EvernoteHelper

    def first_token(path)
      token = path.split('/').select{ |token| !token.blank? }.first
      return '/'  if token.nil? || token.include?('.')
      return "/#{token}/"
    end

    def handle_notebooks(name)
      @page = (params[:page] || '1').to_i
      @notes = get_notes_list(name, @page) || not_found
      if @notes.size > CONFIG['page_size']
        @has_next = true
        @notes = @notes[0...@notes.size - 1]
      end
      respond_to do |format|
        format.html { render 'index' }
        format.atom { render 'index'}
      end
    end
    def handle_note(guid)
      @note = get_note_by_guid(guid, true) || not_found
      render 'show'
    end

    CONTENT_REGEXP = /<en-note[^>]*?>(.+?)<\/en-note>/m
    def extract_content(content)
      CONTENT_REGEXP =~ content
      $1.force_encoding('utf-8')
    end

    def extract_snippet(content)
      Nokogiri::HTML(content).text[0..192]
    end

    IMAGE_REGEXP_STR = '<en-media hash="#md5#" .*? type="image/png".*?/>'
    def embed_images(note)
      return note if note[:resources].nil?
      note[:resources].each do |resource|
        next if resource.data.body.nil? || !resource.mime.start_with?('image/')
        image_regex = Regexp.new(IMAGE_REGEXP_STR.sub('#md5#', resource.data.bodyHash.unpack('H*')[0]))
        note[:content] = note[:content].sub(image_regex, "<img src='data:image/png;base64,#{Base64.encode64(resource.data.body)}'/>")
      end
      note
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def add_trailing_slash(path)
    if path.end_with?('/')
      path
    else
      "#{path}/"
    end
  end

  def atom_feed_links
    CONFIG['header_links'].select do |link|
      link['resource']['type'] == 'notebook'
    end.map do |link|
      auto_discovery_link_tag(:atom, File.join(link['path'], 'feed.atom'), { title: "#{CONFIG['site_name']} #{link['text']}" })
    end.join("\n")
  end
end

app/helpers/evernotes_helper.rb
module EvernotesHelper
  def format_timestamp(timestamp)
    dt = DateTime.strptime((timestamp / 1000).to_s, '%s')
    dt = (dt.to_time + CONFIG['time_zone'].hours).to_datetime
    dt.strftime('%Y-%m-%d %H:%M:%S')
  end
  def show_tags(note)
    return '' if note.nil? || note[:tags].nil? || note[:tags].empty?
    "This entry was tagged #{note[:tags].join(', ')}.".force_encoding('utf-8')
  end
end

app/views/evernote/index.html.erb
<% @notes.each do |note| %>
<%= note.title %><br/>
<% end %>

<hr/>

<%= @note.title %><br/>
<%= @note.content %><br/>

app/views/evernotes/_disqus.html.erb
<br/><br/>
<div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = '<%= CONFIG['disqus']['shortname'] %>';
    var disqus_identifier = '<%= params['created'] %>';
    var disqus_url = '<%= request.original_url %>';

    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>

app/views/evernotes/index.html.erb
<% provide(:title, @title) %>

<% @notes.each do |note| %>
  <div class="row entry-overview">
    <div class="span2 date"><%= raw format_timestamp(note[:created]).split.join('<br/>') %></div>
    <div class="span7">
      <strong><%= link_to(note[:title], note_path(created: note[:created]/1000, trailing_slash: true)) %></strong>
      <br/><%= note[:snippet] %> ...
    </div>
  </div>
<% end %>

<br/>

<div class="row">
<div class="offset3 span4">
<% if @page > 1 %>
<%= link_to('« Previous', "#{add_trailing_slash(request.path)}" + (@page == 2 ? "" : "?page=#{@page - 1}")) %>
<% else %>
« Previous
<% end %>
 — 
<strong><%= @page %></strong>
 — 
<% if @has_next %>
<%= link_to('Next »', "#{add_trailing_slash(request.path)}?page=#{@page + 1}") %>
<% else %>
Next »
<% end %>
</div>
</div>

app/views/evernotes/show.html.erb
<% provide(:title, @note[:title]) %>

<div class="row">
<div class="offset1 span8">
<h1><%= @note[:title] %></h1>
<div class="meta">created at <%= format_timestamp(@note[:created]) %>, updated at <%= format_timestamp(@note[:updated]) %></div>
<div class="tags"><%= show_tags(@note) %></div>
<br/><br/>
<%= raw @note[:content] %>
<%= render 'disqus' %>
</div></div>

app/views/layouts/_debug.html.erb
<% if Rails.env.development? %>
<br/><br/>
<pre class="debug_dump">
method: <%= request.method %>
original_url: <%= request.original_url %>
params: <%= params %>
path: <%= request.path %>
</pre>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
<%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<br/><hr/>
<footer class="footer">
&copy; 2012 all rights reserved, proudly powered by <%= link_to('eversite', 'https://github.com/tylerlong/eversite', target: '_blank') %>.
<span class="pull-right">
Contact me via: <%= raw CONFIG['footer_links'].map { |link| link_to(link['text'], link['url'], target: '_blank') }.join(', ') %>.
</span>
</footer>
<br/><br/>

app/views/layouts/_google_analytics.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', <%= "'#{CONFIG['google_analytics']['tracking_id']}'" %>]);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/layouts/_header.html.erb
<header class="navbar">
<div class="navbar-inner">
<div class="container">
<%= link_to(CONFIG['site_name'], root_path, class: "brand") %>
<ul class="nav pull-right">
<% CONFIG['header_links'].each do |link| %>
  <li class="divider-vertical"></li>
  <li><%= link_to(link.text, add_trailing_slash(link.path)) %></li>
  <% if link.resource.type == 'notebook' %><li>
    <%= link_to(image_tag('feed.png'), File.join(link.path, 'feed.atom'), target: '_blank') %>
  </li><% end %>
<% end %>
</ul>
</div>
</div>
</header>
<br/>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title) %> | <%= CONFIG["site_name"] %></title>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<%= raw atom_feed_links %>
<%= render 'layouts/shim' %>
<%= render 'layouts/google_analytics' %>
</head>
<body>
<div class="container">
<%= render 'layouts/header' %>
<%= render 'layouts/flash', flash: flash %>
<div class="row">
<div class="offset1 span10 bordered">
<%= yield %>
</div></div>
<%= render 'layouts/footer' %>
<%= render 'layouts/debug' %>
</div>
</body>
</html>